/**:
  ros__parameters:   
   
    in_speed: 0.38  # Скорость после знака перекрестка
    speed_L: 0.38   # Скорость при движении по левому повороту
    speed_R: 0.38   # Скорость при движении по правому повороту
    out_speed: 0.40 # Скорость после выезда из перекрестка

    in_offset: -10.0 # Смещение после знака перекрестка
    L_offset: 100.0  # Смещение при повороте налево
    R_offset: 40.0   # Смещение при повороте направо
    out_offset: 50.0 # Смещение после знака перекрестка

    angle_L: 60.0  # Угол поворота налево
    angle_R: -15.0 # Угол поворота направо

    linear_x_L: 0.20 # Линейная скорость при повороте налево
    linear_x_R: 0.20 # Линейная скорость при повороте направо

    angular_z_L: 1.0 # Угловая скорость при повороте налево
    angular_z_R: 1.0 # Угловая скорость при повороте направо