/**:
  ros__parameters:

    # Максимальная скорость робота
    max_speed: 0.20
    
    # Смещение центра от начального центра полосы
    center_offset: 40

    # Размера буфера с ошибками
    max_len: 50 

    # PID константы для угла поворота  
    Kp_ang: 0.005
    Ki_ang: 0.0
    Kd_ang: 0.0

    # PID константы для скорости
    Kp_vel: 0.0
    Ki_vel: 0.0
    Kd_vel: 0.0

    # Минимальная площадь bbox для детекции знака
    min_square: 8000

    # Количество детекций для усреднения ответа
    detects_cnt: 10