/**:
  ros__parameters:

    in_speed: 0.50      # Скорость после детекции знака парковки
    parking_speed: 0.35 # Скорость подьезда к парковочному месту
    out_speed: 0.40     # Скорость после выезда с парковки

    in_offset: 60.0    # Смещение при приближении к парковке
    out_offset: 30.0   # Смещение после выезда с парковки

    angle_L: 85.0  # Угол поворота налево
    angle_R: -80.0 # Угол поворота направо
    angle_B: 70.0  # Угол поворота при выезде задом

    linear_x_L: 0.20   # Линейная скорость при повороте налево
    linear_x_R: 0.28   # Линейная скорость при повороте направо
    linear_x_BL: -0.05 # Линейная скорость при выезде задом налево
    linear_x_BR: -0.10 # Линейная скорость при выезде задом направо

    angular_z_L: 1.0  # Угловая скорость при повороте налево
    angular_z_R: 1.0  # Угловая скорость при повороте направо
    angular_z_BL: 0.5 # Угловая скорость при выезде задом налево
    angular_z_BR: 0.6 # Угловая скорость при выезде задом направо