/**:
  ros__parameters:

    stop_distance: 0.4 # Расстояние до пешехода для реагирования

    in_speed: 0.35  # Скорость после обнаружения знака пешеходного перехода
    out_speed: 0.40 # Скорость после проезда пешехлдного перехода

    in_offset: 20.0  # Смещение после обнаружения знака пешеходного перехода
    out_offset: 30.0 # Смещение после проезда пешехлдного перехода