/**:
  ros__parameters:

    # Целевые координаты
    target_x: -0.8
    target_y: -0.2

    threshold: 0.5 # Порог по расстоянию между точками

    speed: 0.3     # Масимальная скорость движения по туннелю
    out_speed: 0.5 # Скорость после выезда из туннеля

    out_offset: 20.0 # Смещение после выезда с туннеля

    max_distance: 0.8 # Максимальная дистанция для начала объезда препятствий